name: Deploy Website via OIDC

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3    
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.5  # Replace with your version

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole-${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Cache Terraform provider plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf', '**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
            terraform-

      - name: Terraform Init
        run: terraform init --reconfigure -input=false

    #   - name: Terraform validate
    #     run: terraform validate

    #   - name: Terraform Plan
    #     run: terraform plan -out=tfplan

      - name: Terraform Plan & Apply
        run: terraform apply -auto-approve -parallelism=10


